name: Run tests

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Python stuff
        run: poetry install
      - name: Run uptime.py
        run: poetry run ./uptime.py
