name: Run tests

on: push
  #schedule:
  #  - cron: '4/15 * * * *'

jobs:
  check-urls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Python stuff
        run: pip install poetry && poetry install
      - name: Run uptime.py
        run: poetry run ./uptime.py
        env:
          URLS: ${{ vars.URLS }}
